//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceNew.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kamera
    {
        public int kamera_IP { get; set; }
        public Nullable<short> personel_ID { get; set; }
        public Nullable<short> firma_ID { get; set; }
        public string kamera_konum_isimlendirme { get; set; }
    
        public virtual firma firma { get; set; }
        public virtual personel personel { get; set; }
    }
}
