//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceNew.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class facerecEntities : DbContext
    {
        public facerecEntities()
            : base("name=facerecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<firma> firma { get; set; }
        public virtual DbSet<kamera> kamera { get; set; }
        public virtual DbSet<oda> oda { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<personel_birim> personel_birim { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ziyaretci> ziyaretci { get; set; }
    }
}
