//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceNew.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.kamera = new HashSet<kamera>();
            this.ziyaretci = new HashSet<ziyaretci>();
        }
    
        public short personel_ID { get; set; }
        public string kullanıcı_ADI { get; set; }
        public string kullanıcı_sifre { get; set; }
        public string kimlik_numarası { get; set; }
        public Nullable<short> firma_ID { get; set; }
        public string Padsoyad { get; set; }
        public string mail { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public Nullable<short> birim_ID { get; set; }
        public Nullable<System.DateTime> ziyaret_saatleri { get; set; }
        public Nullable<int> maas { get; set; }
        public Nullable<byte> mesai { get; set; }
        public Nullable<short> oda_ID { get; set; }
        public string personel_resim { get; set; }
        public string personel_anahtar { get; set; }
    
        public virtual firma firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kamera> kamera { get; set; }
        public virtual oda oda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ziyaretci> ziyaretci { get; set; }
        public virtual personel_birim personel_birim { get; set; }
        public virtual rapor rapor { get; set; }
    }
}
