//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceNew.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ziyaretci
    {
        public short ziyaretci_ID { get; set; }
        public string kimlik_nu { get; set; }
        public Nullable<short> firma_ID { get; set; }
        public string isimsoyisim { get; set; }
        public string mail { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public Nullable<short> personel_ID { get; set; }
        public string ziyaret_sebebi { get; set; }
        public Nullable<System.DateTime> ziyaret_saati { get; set; }
        public string ziyaretci_resim { get; set; }
        public string ziyaretci_anahtar { get; set; }
        public Nullable<bool> ziyaret_durum { get; set; }
    
        public virtual firma firma { get; set; }
        public virtual personel personel { get; set; }
        public virtual ziyaretci_raporu ziyaretci_raporu { get; set; }
    }
}
