//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceNew.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ziyaretci_raporu
    {
        public short ziyaretci_ID { get; set; }
        public string son_konumu { get; set; }
        public Nullable<System.DateTime> kamera_görüs_saati { get; set; }
        public Nullable<bool> ihlal { get; set; }
    
        public virtual ziyaretci ziyaretci { get; set; }
    }
}
