//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facerecognition.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kamera
    {
        public string kameraip { get; set; }
        public Nullable<short> personelid { get; set; }
        public Nullable<short> firmaid { get; set; }
        public string kamerakonum { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
