//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facerecognition.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbFaceRecEntities : DbContext
    {
        public DbFaceRecEntities()
            : base("name=DbFaceRecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firma> Firma { get; set; }
        public virtual DbSet<Kamera> Kamera { get; set; }
        public virtual DbSet<Oda> Oda { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Rapor> Rapor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ziyaretci> Ziyaretci { get; set; }
        public virtual DbSet<ZiyaretciRapor> ZiyaretciRapor { get; set; }
    }
}
