//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facerecognition.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.Kamera = new HashSet<Kamera>();
            this.Ziyaretci = new HashSet<Ziyaretci>();
        }
    
        public short personelid { get; set; }
        public string kullaniciadi { get; set; }
        public string kullanicisifre { get; set; }
        public string kimlikno { get; set; }
        public Nullable<short> firmaid { get; set; }
        public string personeladi { get; set; }
        public string personelsoyadi { get; set; }
        public string personelmail { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string birimi { get; set; }
        public Nullable<System.DateTime> giriszamani { get; set; }
        public Nullable<System.DateTime> cikiszamani { get; set; }
        public Nullable<System.DateTime> ziyaretsaati { get; set; }
        public Nullable<short> maas { get; set; }
        public Nullable<byte> mesai { get; set; }
        public Nullable<short> odaid { get; set; }
    
        public virtual Firma Firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kamera> Kamera { get; set; }
        public virtual Oda Oda { get; set; }
        public virtual Rapor Rapor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ziyaretci> Ziyaretci { get; set; }
    }
}
