//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facerecognition.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rapor
    {
        public short personelid { get; set; }
        public Nullable<System.DateTime> giriszamani { get; set; }
        public Nullable<System.DateTime> cikiszamani { get; set; }
        public string sonkonum { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
