//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facerecognition.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ziyaretci
    {
        public short ziyaretciid { get; set; }
        public string kimlikno { get; set; }
        public Nullable<short> firmaid { get; set; }
        public string ziyaretciadi { get; set; }
        public string ziyaretcisoyadi { get; set; }
        public string mail { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public Nullable<short> personelid { get; set; }
        public string ziyaretsebebi { get; set; }
        public Nullable<System.DateTime> ziyaretzamani { get; set; }
        public Nullable<bool> ziyaretdurum { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual ZiyaretciRapor ZiyaretciRapor { get; set; }
    }
}
