//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facerecognition.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZiyaretciRapor
    {
        public short ziyaretciid { get; set; }
        public string sonkonum { get; set; }
        public Nullable<System.DateTime> kameragorussaati { get; set; }
        public Nullable<bool> ihlaldurum { get; set; }
    
        public virtual Ziyaretci Ziyaretci { get; set; }
    }
}
